### ISSUE TITLE
Multiple Domains SAN

### ISSUE THREAD

**Issue by Yamakasi** [analogic/lescript#10]
Is it possible to create a SAN using a list ?

**Comment by analogic** [comment]
Sure $le->signDomains(array('test.com', 'www.test.com', 'anotherdomain.com', 'yedomain.com'...));

**Comment by Yamakasi** [comment]
Merci!

**Comment by Yamakasi** [comment]
Hi as far as I see this creates a certifcate per domain and not one domain containing all domains as AltNames.

**Comment by splitbrain** [comment]
I think this issue should be reopened.

**Comment by splitbrain** [comment]
Never mind, passing multiple domains works indeed. For everyone wondering else, wondering here's the part in the code: https://github.com/analogic/lescript/blob/master/Lescript.php#L259
