### ISSUE TITLE
Cert Renew

### ISSUE THREAD

**Issue by futureweb** [analogic/lescript#13]
It would be cool if lescript would handle CERT renew ... one could simply check if CERT is valid less then X (configureable) Days ... if yes - renew - otherwise do nothing ...

some code snippets I use in my Script for this:
`$certinfo = openssl_x509_parse(file_get_contents($sslCertPath."/".$domain."/cert.pem"));`
`
if(!isset($certinfo) || $certinfo['validFrom_time_t'] > time() || $certinfo['validTo_time_t'] < time()+(60*60*24*$renewDaysBeforeExpire)){`
`    DO RENEW`
`}  else { DO NOTHING } `

Andreas Schnederle-Wagner

**Comment by harishningegowda** [comment]
That would be awesome if someone can come up with the renewal process.

**Comment by xrobau** [comment]
I've just submitted pull request #15 which implements this request. Seems to work for me.

Thanks to @tm1000 for harassing me into writing this.
