### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by schultz-it-solutions** [analogic/lescript#14]
Hello Stanislav,

I am trying to implement your library on our server, in order to automate the „letsencrypt“ services. However my knowledge of „letsencrypt“ is a bit limited, and almost all information available refers to LINUX installations
I am running an Apache 2.4 server on a Windows 2012 server environment – and this is working very well so far. SSL is successfully established (e.g https://it-solutions.schultz.ch), but we use certificates from CACert.org so far – and I decided to switch to „lets-encrypt“ now.

So I know what to do with domain certificates once I have them, but my understanding of the „letsencrypt“ process and the ACME protocols are limited.

When I submit the „signDomains“ function for e.g. „demo.schultz.ch“ I get the following messages:
Account already registered. 
Continuing. 
Starting certificate generation process for domains 
Requesting challenge for demo.schultz.ch 
Error occured: Curl: SSL certificate problem: unable to get local issuer certificate
## Details: ###
0 ...letsencrypt\Lescript.php(451): Analogic\ACME\Client->curl('GET', '/directory') 
...

My linenumbers slightly differ from the github master (445)

can you give any advice please

**Comment by futureweb** [comment]
Hi Rüdiger,

it might be a problem with CURL & Windows - you might check this out: https://www.zen-cart.com/showthread.php?213892-Windows-server-Curl-error-%2860%29-SSL-Certificate-problem-Unable-to-get-local-issuer

(https://www.google.at/search?q=windows+iis+Curl:+SSL+certificate+problem:+unable+to+get+local+issuer+certificate&ie=utf-8)

Hope it helps ;-)
Andreas Schnederle-Wagner

**Comment by schultz-it-solutions** [comment]
Das klingt vielversprechend, werde mir das anschauen…

Danke!!!!

 

 

Von: Andreas Schnederle-Wagner [mailto:notifications@github.com] 
Gesendet: Mittwoch, 23. März 2016 15:19
An: analogic/lescript <lescript@noreply.github.com>
Cc: Ruediger Schultz <it-solutions@schultz.ch>
Betreff: Re: [lescript] SSL certificate problem: unable to get local issuer certificate (#14)

 

Hi Rüdiger,

it might be a problem with CURL & Windows - you might check this out: https://www.zen-cart.com/showthread.php?213892-Windows-server-Curl-error-%2860%29-SSL-Certificate-problem-Unable-to-get-local-issuer

(https://www.google.at/search?q=windows+iis+Curl:+SSL+certificate+problem:+unable+to+get+local+issuer+certificate <https://www.google.at/search?q=windows+iis+Curl:+SSL+certificate+problem:+unable+to+get+local+issuer+certificate&ie=utf-8> &ie=utf-8)

Hope it helps ;-)
Andreas Schnederle-Wagner

**Comment by schultz-it-solutions** [comment]
Hello Andreas,
Actually, this seemed to solve my issue (although I am running an APACHE webserver on windows, and not IIS). I am able now to receive the challange-token...
Thank you!
