### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by mikebronner** [analogic/lescript#20]
![screen shot 2016-08-17 at 13 57 52](https://cloud.githubusercontent.com/assets/1791050/17752954/01f655c4-6483-11e6-885d-c7133afad519.png)

**Comment by analogic** [comment]
you were not using analogic/lescript :)

**Comment by mikebronner** [comment]
It says it right in the filename?

**Comment by mikebronner** [comment]
Upgrading to v 0.1.4 fixed it. I will let the package maintainer that uses your package know to update. Thanks. :)
