### ISSUE TITLE
_auto_example.php wrong

### ISSUE THREAD

**Issue by splitbrain** [analogic/lescript#24]
Unless I'm mistaken, it seems that the _auto_example does not do what it is supposed to do. Here is what it does as far as I understand:
- for each domain in `$domains`, it checks if it finds a separate certificate (in `$certlocation/$d/cert.pem`)
  - if yes, it checks the expiry date of that certificate, if less than 30 days, `$needsgen` is set to true
  - if no, `$needsgen` is set to true
- when `$needsgen` is true, `$le->signDomains($domains)` is called

The problem is that `$le->signDomains($domains)` creates only _one_ certificate (using the first domain in $domains) with all remaining domains as SAN. So the above check will always set `$needsgen` = true since there are no individual certificates for all the domains.

Am I missing something?

**Comment by Humni** [comment]
Looks like a bug to me too. I believe it should be checking if there is a certificate for the first domain in the array, and then checking if the certificate contains every other domain in the array as a SAN. However, the example does work for single domain registrations.
