### ISSUE TITLE
Getting Error on Windows

### ISSUE THREAD

**Issue by bkrajendra** [analogic/lescript#27]
I always get error while running this script on Windows+Apache+PHP
```
Warning: openssl_pkey_export(): cannot get key from parameter 1 in H:\xampp\htdocs\letsencrypt\lescript-master\Lescript.php on line 330
2016-11-17 00:07:24 [error] Key export failed!
2016-11-17 00:07:24 [error] #0 H:\xampp\htdocs\letsencrypt\lescript-master\Lescript.php(41): Analogic\ACME\Lescript->generateKey('/letsencrypt/le...')
#1 H:\xampp\htdocs\letsencrypt\lescript-master\_example.php(20): Analogic\ACME\Lescript->initAccount()
#2 {main}
```

**Comment by bkrajendra** [comment]
I got it resolved by following steps:
On windows 
1. Go to SYSTEM
2. Click on ADVANCED SYSTEM SETTINGS
3. Click on ENVIRONMENT VARIABLES
4. Under "System Variables" click on "NEW"
5. Enter the "Variable name" OPENSSL_CONF
6. Enter the "Variable value". My is - C:\xampp\apache\conf\openssl.cnf
7. Click "OK" and close all the windows and RESTART your computer.

Everything Started working fine.

**Comment by Humni** [comment]
This should be closed as it is revolved.
