### ISSUE TITLE
Wildcard names not supported

### ISSUE THREAD

**Issue by bateller** [analogic/lescript#35]
Tried to use Lescript to create a Wildcard certificate.

Not surprisingly, it didn't work.

Lets Encrypt added support for Wildcard domains recently:
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by Humni** [comment]
lescript currently isn't updated to support wild card domains

**Comment by futureweb** [comment]
guess it won't support wildcards ever ... as they need DNS-01 Challenge .... but lescript only supports HTTP-01 ...
